### ISSUE TITLE
Test if portal (open or closed)

### ISSUE THREAD

**Issue by nicopollux** [panukettu/pet-gotchis#1]
If the owner also has open or closed portals in his inventory, the script will fail. 
One test could be to remove a record when tokenId == 0
https://github.com/panukettu/pet-gotchis/blob/b18b9c83f5c3aec1154b0616c51e2bccc5cb77bd/scripts/setOperatorAndPet.ts#L74

**Comment by panukettu** [comment]
Are you referring to the actual owner of the gotchis or the delegated petter having portals? I do have unopened portals on my main but not the account who does the petting and seems to work. Can look into at some point.

**Comment by nicopollux** [comment]
When you call tokenIdsWithKinship, it returns Gotchis as well as portals

**Comment by panukettu** [comment]
this fixed btw
